#!/usr/bin/env bash
# Install aerox9ctl for the current user, on the host or inside a distrobox container.
#
#   ./install.sh               install (or upgrade) CLI + GUI + app menu entry
#   ./install.sh --editable    same, but run straight from this source tree
#   ./install.sh --daemon      also enable the lighting daemon (systemd user service)
#   ./install.sh --tray        also start the battery tray icon at login
#   ./install.sh --uninstall   remove everything this script installed
#
# Inside distrobox, the launchers it creates in ~/.local/bin run the tool through
# `distrobox-enter`, so `aerox9ctl` and the menu entry work from the host too.
set -euo pipefail

SRC="$(cd "$(dirname "$0")" && pwd)"
DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
BIN_DIR="$HOME/.local/bin"
DESKTOP_FILE="$DATA_HOME/applications/aerox9ctl.desktop"
UNIT_FILE="$CONFIG_HOME/systemd/user/aerox9ctl-daemon.service"
AUTOSTART_FILE="$CONFIG_HOME/autostart/aerox9ctl-tray.desktop"

CONTAINER=""
if [ -f /run/.containerenv ]; then
    CONTAINER="$(sed -n 's/^name="\(.*\)"$/\1/p' /run/.containerenv)"
fi
# One venv per environment: host and containers can have different Python versions.
VENV="$DATA_HOME/aerox9ctl/venv${CONTAINER:+-$CONTAINER}"

editable=0 daemon=0 tray=0 uninstall=0
for arg in "$@"; do
    case "$arg" in
        --editable) editable=1 ;;
        --daemon) daemon=1 ;;
        --tray) tray=1 ;;
        --uninstall) uninstall=1 ;;
        -h|--help) sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
        *) echo "unknown option: $arg" >&2; exit 2 ;;
    esac
done

# systemctl --user must run on the host
host_systemctl() {
    if [ -n "$CONTAINER" ]; then
        distrobox-host-exec systemctl --user "$@"
    else
        systemctl --user "$@"
    fi
}

if [ "$uninstall" = 1 ]; then
    if [ -f "$UNIT_FILE" ]; then
        host_systemctl disable --now aerox9ctl-daemon.service 2>/dev/null || true
        rm -f "$UNIT_FILE"
        host_systemctl daemon-reload || true
    fi
    rm -f "$BIN_DIR/aerox9ctl" "$BIN_DIR/aerox9ctl-gui" "$BIN_DIR/aerox9ctl-tray" "$DESKTOP_FILE" "$AUTOSTART_FILE"
    rm -rf "$VENV"
    echo "Uninstalled. Settings and profiles are kept in $CONFIG_HOME/aerox9ctl."
    exit 0
fi

echo "==> Creating virtualenv in $VENV"
python3 -m venv "$VENV"
"$VENV/bin/python" -m pip install --quiet --upgrade pip
if [ "$editable" = 1 ]; then
    "$VENV/bin/python" -m pip install --quiet --editable "$SRC[gui]"
else
    "$VENV/bin/python" -m pip install --quiet "$SRC[gui]"
fi

echo "==> Writing launchers to $BIN_DIR"
mkdir -p "$BIN_DIR"
for name in aerox9ctl aerox9ctl-gui aerox9ctl-tray; do
    if [ -n "$CONTAINER" ]; then
        cat > "$BIN_DIR/$name" <<EOF
#!/bin/sh
# Generated by aerox9ctl install.sh: runs $name inside the "$CONTAINER" distrobox.
if [ -f /run/.containerenv ] && grep -qx 'name="$CONTAINER"' /run/.containerenv; then
    exec "$VENV/bin/$name" "\$@"
fi
exec distrobox-enter -n "$CONTAINER" -- "$VENV/bin/$name" "\$@"
EOF
    else
        cat > "$BIN_DIR/$name" <<EOF
#!/bin/sh
# Generated by aerox9ctl install.sh
exec "$VENV/bin/$name" "\$@"
EOF
    fi
    chmod +x "$BIN_DIR/$name"
done

echo "==> Adding app menu entry"
mkdir -p "$(dirname "$DESKTOP_FILE")"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Aerox 9 Wireless
GenericName=Mouse Settings
Comment=Configure the SteelSeries Aerox 9 Wireless mouse
Exec=$BIN_DIR/aerox9ctl-gui
Icon=input-mouse
Terminal=false
Categories=Settings;HardwareSettings;
Keywords=steelseries;mouse;dpi;rgb;
StartupWMClass=aerox9ctl
EOF

if [ "$tray" = 1 ]; then
    echo "==> Starting the tray icon at login"
    mkdir -p "$(dirname "$AUTOSTART_FILE")"
    cat > "$AUTOSTART_FILE" <<EOF
[Desktop Entry]
Type=Application
Name=Aerox 9 Battery
Comment=Battery level of the SteelSeries Aerox 9 Wireless in the system tray
Exec=$BIN_DIR/aerox9ctl-tray
Icon=input-mouse
Terminal=false
X-GNOME-Autostart-enabled=true
EOF
fi

mkdir -p "$(dirname "$UNIT_FILE")"
sed "s|@BIN_DIR@|$BIN_DIR|" "$SRC/packaging/aerox9ctl-daemon.service" > "$UNIT_FILE"
if [ "$daemon" = 1 ]; then
    echo "==> Enabling the lighting daemon"
    host_systemctl daemon-reload
    host_systemctl enable --now aerox9ctl-daemon.service
fi

echo
echo "Done. Run 'aerox9ctl status' or open 'Aerox 9 Wireless' from the app menu."
if [ "$tray" = 1 ]; then echo "Tray icon: starts at next login, or run 'aerox9ctl-tray &' now."; fi
if [ "$daemon" = 0 ]; then
    echo "To restore static colors automatically after sleep/power-off:"
    echo "  systemctl --user enable --now aerox9ctl-daemon.service   (on the host)"
fi
case ":$PATH:" in *":$BIN_DIR:"*) ;; *) echo "Note: $BIN_DIR is not in your PATH." ;; esac
